# Generated by Django 3.2.3 on 2021-06-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='tags',
            field=models.ManyToManyField(blank=True, to='resumes.Tag'),
        ),
    ]
